# Generated by Django 3.2 on 2021-04-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_cadastro',
            new_name='data_criacao',
        ),
    ]
